use Mix.Config

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :mokou, Mokou.Endpoint,
  url: [host: "ticket.harimusic.net", port: 443],
  https: [port: 443,
          keyfile: "/etc/letsencrypt/live/ticket.harimusic.net/privkey.pem",
          certfile: "/etc/letsencrypt/live/ticket.harimusic.net/fullchain.pem"
  ],
  force_ssl: true,
  cache_static_manifest: "priv/static/manifest.json"

config :mokou,
  limit_of_count: 1400,
  end_date: "2017-09-21T00:00:00Z"

# Configure your database
config :mokou, Mokou.Repo,
  adapter: Ecto.Adapters.MySQL,
  username: System.get_env("MOKOU_DB_USERNAME"),
  password: System.get_env("MOKOU_DB_PASSWORD"),
  database: "mokou",
  hostname: "localhost",
  pool_size: 10

# mailer
config :mokou, Mokou.Mailer,
  adapter: Bamboo.SMTPAdapter,
  server: "m.s01.info",
  port: 465,
  username: System.get_env("MOKOU_SMTP_USERNAME"),
  password: System.get_env("MOKOU_SMTP_PASSWORD"),
  tls: :if_available, # can be `:always` or `:never`
  ssl: true, # can be `true`
  retries: 1


# Do not print debug messages in production
config :logger, level: :info

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :mokou, Mokou.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [port: 443,
#               keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#               certfile: System.get_env("SOME_APP_SSL_CERT_PATH")]
#
# Where those two env variables return an absolute path to
# the key and cert in disk or a relative path inside priv,
# for example "priv/ssl/server.key".
#
# We also recommend setting `force_ssl`, ensuring no data is
# ever sent via http, always redirecting to https:
#
#     config :mokou, Mokou.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# ## Using releases
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start the server for all endpoints:
#
#     config :phoenix, :serve_endpoints, true
#
# Alternatively, you can configure exactly which server to
# start per endpoint:
#
#     config :mokou, Mokou.Endpoint, server: true
#

# Finally import the config/prod.secret.exs
# which should be versioned separately.
import_config "prod.secret.exs"
